- task: MSBuild@1
  displayName: Build project [% project %]
  inputs:
    solution: '[% project %]'
    [% IF platform %]
    platform: [% platform %]
    [% END %]
    [% IF configuration %]
    configuration: [% configuration %]
    [% END %]
    msbuildArguments: '/p:OutDir="$(build.artifactstagingdirectory)"'

